import { formatDate } from "./helpers.js";

const STORAGE_KEY = "setting";
const DEFAULT_SETTING = {
  token: "",
  search: "",
  locale: ["us"],
  language: ["en"],
  categories: [],
  sort: "published_at",
  dateFilter: "published_on",
  date: formatDate(new Date()),
  news: [],
};
const CATEGORIES_OPTIONS = [
  "general",
  "science",
  "sports",
  "business",
  "health",
  "entertainment",
  "tech",
  "politics",
  "food",
  "travel",
];
const LOCALE_OPTIONS = {
  ar: "Argentina",
  am: "Armenia",
  au: "Australia",
  at: "Austria",
  by: "Belarus",
  be: "Belgium",
  bo: "Bolivia",
  br: "Brazil",
  bg: "Bulgaria",
  ca: "Canada",
  cl: "Chile",
  cn: "China",
  co: "Colombia",
  hr: "Croatia",
  cz: "Czechia",
  ec: "Ecuador",
  eg: "Egypt",
  fr: "France",
  de: "Germany",
  gr: "Greece",
  hn: "Honduras",
  hk: "Hong Kong",
  in: "India",
  id: "Indonesia",
  ir: "Iran",
  ie: "Ireland",
  il: "Israel",
  it: "Italy",
  jp: "Japan",
  kr: "Korea",
  mx: "Mexico",
  nl: "Netherlands",
  nz: "New Zealand",
  ni: "Nicaragua",
  pk: "Pakistan",
  pa: "Panama",
  pe: "Peru",
  pl: "Poland",
  pt: "Portugal",
  qa: "Qatar",
  ro: "Romania",
  ru: "Russia",
  sa: "Saudi Arabia",
  za: "South Africa",
  es: "Spain",
  ch: "Switzerland",
  sy: "Syria",
  tw: "Taiwan",
  th: "Thailand",
  tr: "Turkey",
  ua: "Ukraine",
  gb: "United Kingdom",
  us: "United States of America",
  uy: "Uruguay",
  ve: "Venezuela",
};

export { STORAGE_KEY, DEFAULT_SETTING, CATEGORIES_OPTIONS, LOCALE_OPTIONS };
